version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/handoff/src"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/compose"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/handoff/src"
    schedule:
      interval: "weekly"
