apiVersion: v1
kind: Service
metadata:
  name: {{ include "stremiarr.fullname" . }}-handoff
  labels:
    {{- include "stremiarr.labels" . | nindent 4 }}
    app.kubernetes.io/component: handoff
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.handoff.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "stremiarr.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: handoff
