apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stremiarr.fullname" . }}-postgres-secret
  labels:
    {{- include "stremiarr.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-user: {{ .Values.postgres.credentials.user | b64enc | quote }}
  postgres-password: {{ .Values.postgres.credentials.password | b64enc | quote }}
